from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

from datetime import date
from app.database.models import CallLog, Student
from sqlalchemy import func
import os


# 🔥 Watermark + Footer + Page Number
def add_design(canvas_obj, doc):
    canvas_obj.saveState()

    # Watermark
    canvas_obj.setFont("Helvetica-Bold", 80)
    canvas_obj.setFillColorRGB(0.9, 0.9, 0.9)
    canvas_obj.translate(300, 400)
    canvas_obj.rotate(45)
    canvas_obj.drawCentredString(0, 0, "CMRTC")

    canvas_obj.restoreState()

    # Footer
    canvas_obj.setFont("Helvetica", 8)
    canvas_obj.drawString(30, 20, "Confidential – CMRTC Internal Use Only")

    # Page Number
    page_number_text = f"Page {doc.page}"
    canvas_obj.drawRightString(580, 20, page_number_text)


def generate_daily_report(db, report_date):

    logs = (
        db.query(CallLog, Student)
        .join(Student, CallLog.student_id == Student.id)
        .filter(CallLog.call_date == report_date)
        .all()
    )

    # ✅ TOTAL CALLS
    total_calls = db.query(func.count(CallLog.id)).filter(
        CallLog.call_date == report_date
    ).scalar()

    os.makedirs("reports", exist_ok=True)
    filename = f"daily_report_{report_date}.pdf"
    filepath = os.path.join("reports", filename)

    doc = SimpleDocTemplate(filepath, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()

    # 🔰 Logo
    logo_path = "assets/cmrtc_logo.png"
    if os.path.exists(logo_path):
        logo = Image(logo_path, width=1.3 * inch, height=1.3 * inch)
        elements.append(logo)

    elements.append(Spacer(1, 0.2 * inch))

    elements.append(Paragraph("<b>CMR Technical Campus</b>", styles["Title"]))
    elements.append(Paragraph(f"Daily Absentee Call Report - {report_date}", styles["Heading2"]))
    elements.append(Spacer(1, 0.2 * inch))

    # ✅ ADD TOTAL CALLS
    elements.append(Paragraph(f"<b>Total Calls Made:</b> {total_calls}", styles["Normal"]))
    elements.append(Spacer(1, 0.3 * inch))

    # 📊 Table
    data = [[
        "Student Name",
        "Parent Number",
        "Transcript",
        "Category",
        "Risk"
    ]]

    if logs:
        for call_log, student in logs:
            data.append([
                student.name,
                student.parent_phone,
                (call_log.transcript_text or "No Response")[:70],
                call_log.excuse_category or "N/A",
                call_log.risk_level or "LOW"
            ])
    else:
        data.append(["No records found", "", "", "", ""])

    table = Table(data, repeatRows=1, colWidths=[90, 90, 170, 70, 50])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
    ]))

    elements.append(table)

    # ✅ SIGNATURE BLOCK
    elements.append(Spacer(1, 0.5 * inch))
    elements.append(Paragraph("Generated By: Automated Caller Bot System", styles["Normal"]))
    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph("Approved By: ____________________________", styles["Normal"]))
    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph(f"Date: {date.today()}", styles["Normal"]))

    doc.build(elements, onFirstPage=add_design, onLaterPages=add_design)

    return filepath